resources:
- ../../base

namespace: prod

patches:
- path: env-patch-deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: workflows

#增加deployment的环境变量配置信息
configMapGenerator:
- name: env-configmap
  literals:
  - JAVA_TOOL_OPTIONS='-javaagent:/skywalking/agent/skywalking-agent.jar'
  - SW_AGENT_NAME='workflows'


