#增加labels
- op: add
  path: /metadata/labels/api
  value: iapi
- op: add
  path: /spec/template/metadata/labels/api
  value: iapi
#更改副本数
- op: replace
  path: /spec/replicas
  value: 1

#增加skywalking配置
- op: add
  path: /spec/template/spec/volumes
  value:
      - name: skywalking-agent
        emptyDir: {}
- op: add
  path: /spec/template/spec/initContainers
  value:
      - name: agent-container
        image: swr.cn-east-3.myhuaweicloud.com/livechamp-cn-v2/sw-agent-java:8.16.0-java8-v5
        command:
          - /bin/sh
        args:
          - '-c'
          - cp -R /skywalking/agent /agent/
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
          - name: skywalking-agent
            mountPath: /agent
        imagePullPolicy: IfNotPresent

