apiVersion: v1
kind: Service
metadata:
  name: livechamp-patchdata-report-svc
  labels:
    app: livechamp-patchdata-report
spec:
  selector:
    app: livechamp-patchdata-report
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
  type: ClusterIP
