apiVersion: v1
kind: Service
metadata:
  name: workflows-svc
  labels:
    app: workflows
spec:
  selector:
    app: workflows
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
  type: ClusterIP
